#!/bin/sh

. /usr/libexec/cudy-port-autodetect/common.sh

case "$1" in
	configure) configure_network ;;
	daemon) run_daemon ;;
	status)
		if [ -r "$RUN_DIR/status.json" ]; then
			cat "$RUN_DIR/status.json"
		else
			echo '网口自动识别服务尚未运行。' >&2
			exit 1
		fi
		;;
	restore) restore_network ;;
	*)
		echo '用法：cudy-port-autodetect status|restore|configure|daemon' >&2
		exit 1
		;;
esac
