#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	[ "$(uci -q get cudy-port-autodetect.main.enabled)" = 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/cudy-port-autodetect daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 15
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger cudy-port-autodetect network
}
