#!/bin/sh

# 探测只记录租约，不能安装地址或路由，也不能执行服务器提供的文本。
case "$1" in bound|renew) ;; *) exit 0 ;; esac
case "$interface" in eth0|eth1) ;; *) exit 1 ;; esac
[ -n "$CUDY_PROBE_DIR" ] && [ -d "$CUDY_PROBE_DIR" ] || exit 1

printf '%s\n' "$ip" "$subnet" "$router" "$staticroutes" \
	> "$CUDY_PROBE_DIR/$interface.lease.tmp" || exit 1
mv "$CUDY_PROBE_DIR/$interface.lease.tmp" "$CUDY_PROBE_DIR/$interface.lease"
